name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'

permissions:
  contents: read

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Adjust Python sys.path
      run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
    - name: Print Python sys.path
      run: python -c "import sys; print(sys.path)"
    - name: Check code with isort
      run: |
        pip install isort
        isort --profile black *.py tests/*
    - name: Check code with Black
      run: |
        pip install black==23.3.0
        black --check .
    - name: Test with pytest
      working-directory: .
      run: |
        pytest -n auto --cov=. --cov-report term --cov-report html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
